package yanovski.billsmanager.daogen;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CURRENCY.
 */
public class Currency implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String symbol;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Currency() {
    }

    public Currency(Long id) {
        this.id = id;
    }

    public Currency(Long id, String name, String symbol) {
        this.id = id;
        this.name = name;
        this.symbol = symbol;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getSymbol() {
        return symbol;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
